# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7vx485tffg1761-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/marisa/PlanA_MarisaOliveira/PlanA_MarisaOliveira.cache/wt [current_project]
set_property parent.project_path C:/Users/marisa/PlanA_MarisaOliveira/PlanA_MarisaOliveira.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet C:/Users/marisa/PlanA_MarisaOliveira/PlanA_MarisaOliveira.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files C:/Users/marisa/PlanA_MarisaOliveira/PlanA_MarisaOliveira.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/marisa/PlanA_MarisaOliveira/PlanA_MarisaOliveira.srcs/sources_1/new/imageGenerator.v
  C:/Users/marisa/PlanA_MarisaOliveira/PlanA_MarisaOliveira.srcs/sources_1/new/top.v
}
read_xdc C:/Users/marisa/PlanA_MarisaOliveira/PlanA_MarisaOliveira.srcs/constrs/new/imageGenerator.xdc
set_property used_in_implementation false [get_files C:/Users/marisa/PlanA_MarisaOliveira/PlanA_MarisaOliveira.srcs/constrs/new/imageGenerator.xdc]

synth_design -top top -part xc7vx485tffg1761-3
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
